name: Node.js CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "PORT=3000" >> .env
          echo "MONGODB_URI=mongodb://localhost:27017/test-event-planner" >> .env
          echo "JWT_SECRET=test-secret-key" >> .env
          echo "EMAIL_SERVICE=test" >> .env
          echo "EMAIL_USER=test@example.com" >> .env
          echo "EMAIL_PASSWORD=test-password" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Run tests
        run: npm test
        env:
          CI: true
          PORT: 3000
          MONGODB_URI: mongodb://localhost:27017/test-event-planner
          JWT_SECRET: test-secret-key
          EMAIL_SERVICE: test
          EMAIL_USER: test@example.com
          EMAIL_PASSWORD: test-password
          NODE_ENV: test
